[workspace]
resolver = "3"

members = ["build", "utils", "year2023", "year2024"]

[workspace.dependencies]
crossterm = "0.29.0"
glob = "0.3.1"
num-bigint = "0.4.6"
rayon = "1.11.0"
regex = "1.9.6"
reqwest = "0.12.28"
tokio = "1.48.0"
