[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
num-bigint = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }

[build-dependencies]
build = { path = "../build" }
